# Generated by Django 5.2.4 on 2025-07-31 04:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('opening_template', models.TextField(help_text='Opening section template')),
                ('strength_template', models.TextField(help_text='Strengths section template')),
                ('improvement_template', models.TextField(help_text='Improvements section template')),
                ('emotion_template', models.TextField(help_text='Emotion feedback template')),
                ('closing_template', models.TextField(help_text='Closing section template')),
                ('tone', models.CharField(default='professional', max_length=20)),
                ('complexity_level', models.IntegerField(default=3, help_text='1=Basic, 5=Advanced')),
                ('focus_areas', models.JSONField(default=list, help_text='Primary focus areas for this model')),
                ('usage_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('junior', 'Junior (2-4 years)'), ('mid', 'Mid Level (4-7 years)'), ('senior', 'Senior (7-12 years)'), ('lead', 'Lead/Manager (12+ years)'), ('executive', 'Executive/C-Level')], default='mid', max_length=20)),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('consulting', 'Consulting'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('government', 'Government'), ('nonprofit', 'Non-Profit'), ('other', 'Other')], default='technology', max_length=20)),
                ('role_type', models.CharField(choices=[('technical', 'Technical/Engineering'), ('product', 'Product Management'), ('sales', 'Sales/Business Development'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('finance', 'Finance/Accounting'), ('hr', 'Human Resources'), ('design', 'Design/Creative'), ('management', 'Management/Leadership'), ('other', 'Other')], default='technical', max_length=20)),
                ('current_job_title', models.CharField(blank=True, max_length=100)),
                ('target_role', models.CharField(blank=True, max_length=100)),
                ('preferred_feedback_model', models.CharField(choices=[('coaching', 'Coaching Style - Supportive and developmental'), ('peer_review', 'Peer Review - Collaborative and balanced'), ('expert_analysis', 'Expert Analysis - Technical and detailed'), ('strategic', 'Strategic Focus - Big picture and leadership'), ('adaptive', 'Adaptive - Automatically adjust based on performance')], default='adaptive', max_length=20)),
                ('learning_preference', models.CharField(choices=[('detailed', 'Detailed - I want comprehensive feedback'), ('concise', 'Concise - Give me the key points quickly'), ('structured', 'Structured - Use frameworks and templates'), ('conversational', 'Conversational - Natural, discussion-style'), ('data_driven', 'Data-Driven - Show me metrics and scores')], default='detailed', max_length=20)),
                ('feedback_complexity', models.IntegerField(default=3, help_text='1=Basic, 5=Advanced')),
                ('interview_goals', models.TextField(blank=True, help_text='What are your interview goals?')),
                ('focus_areas', models.JSONField(default=list, help_text='Areas to focus on (JSON list)')),
                ('weak_areas', models.JSONField(default=list, help_text='Areas needing improvement (JSON list)')),
                ('session_count', models.IntegerField(default=0)),
                ('total_practice_time', models.DurationField(default=datetime.timedelta)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('preferred_question_types', models.JSONField(default=list)),
                ('performance_history', models.JSONField(default=dict, help_text='Historical performance data')),
                ('engagement_metrics', models.JSONField(default=dict, help_text='User engagement patterns')),
                ('feedback_effectiveness', models.JSONField(default=dict, help_text='Feedback model effectiveness scores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('profile_completion', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('behavioral', 'Behavioral'), ('technical', 'Technical'), ('situational', 'Situational'), ('motivational', 'Motivational')], max_length=20)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('overall_score', models.FloatField(default=0.0)),
                ('content_score', models.FloatField(default=0.0)),
                ('emotion_score', models.FloatField(default=0.0)),
                ('delivery_score', models.FloatField(default=0.0)),
                ('detected_emotion', models.CharField(default='neutral', max_length=20)),
                ('validated_emotion', models.CharField(default='neutral', max_length=20)),
                ('emotion_confidence', models.FloatField(default=0.0)),
                ('emotion_corrections', models.IntegerField(default=0)),
                ('feedback_model_used', models.CharField(default='adaptive', max_length=20)),
                ('feedback_content', models.TextField()),
                ('feedback_generated_at', models.DateTimeField(auto_now_add=True)),
                ('user_rating', models.IntegerField(blank=True, help_text='1-5 rating of feedback quality', null=True)),
                ('user_notes', models.TextField(blank=True)),
                ('processing_time', models.FloatField(default=0.0)),
                ('vectorizer_used', models.BooleanField(default=False)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='interview.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
